name: Update Redirect HTMLs

on:
  push:
    branches:
      - main # or your default branch, e.g., 'master'
    paths:
      - 'redirects.json'             # Trigger when the config file changes
      - 'public/**/*'                # !!! UPDATED: Trigger when ANY file in the 'public' directory changes !!!

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Still needed for git-auto-commit-action

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Jinja2
      run: pip install Jinja2

    - name: Auto-generate redirects.json and HTML files
      id: generate_html
      run: python .github/scripts/auto_generate_redirects.py

    - name: Debug generated files and output
      run: |
        echo "--- Debugging 'generate_html' step outputs ---"
        echo "--- Listing contents of ROOT_CONTENT_DIRECTORY (public) ---"
        ls -la "public/" || echo "public/ directory not found or empty." # !!! UPDATED DEBUG PATH !!!
        echo "--- Listing contents of the root directory ---"
        ls -la

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "feat: Auto-generate redirect HTMLs and update redirects.json"
        file_pattern: '.'
        branch: main # or your default branch, e.g., 'master'
