name: Update Redirect HTMLs

on:
  push:
    branches:
      - main # or your default branch, e.g., 'master'
    paths:
      - 'redirects.json' # Trigger when the config file changes

jobs:
  build:
    runs-on: ubuntu-latest
    # --- ADD THIS PERMISSIONS BLOCK ---
    permissions:
      contents: write
    # ---------------------------------

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Jinja2
      run: pip install Jinja2

    - name: Generate redirect HTML files
      id: generate_html
      run: python .github/scripts/generate_redirects.py

    - name: Debug generated files and output
      run: |
        echo "--- Debugging 'generate_html' step outputs ---"
        echo "Generated files output: ${{ steps.generate_html.outputs.generated_files }}"

        echo "--- Listing contents of the target directory ---"
        ls -la "Workshops/Advanced Machine Learning - Extend Operational Insights/" || echo "Target directory not found or empty."
        echo "--- Listing contents of Workshops/ (for general overview) ---"
        ls -la Workshops/
        echo "--- Listing contents of the root directory ---"
        ls -la

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "feat: Auto-generate redirect HTMLs based on redirects.json"
        file_pattern: ${{ steps.generate_html.outputs.generated_files }}
        branch: main # or your default branch, e.g., 'master'
