name: Update Redirect HTMLs

on:
  push:
    branches:
      - main # or your default branch, e.g., 'master'
    paths:
      - 'redirects.json' # Trigger when the config file changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Jinja2
      run: pip install Jinja2

    - name: Generate redirect HTML files
      id: generate_html
      # Now we just execute the Python script directly
      run: python .github/scripts/generate_redirects.py

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "feat: Auto-generate redirect HTMLs based on redirects.json"
        # Use the output from the Python script to specify which files to commit
        file_pattern: ${{ steps.generate_html.outputs.generated_files }}
        branch: main # or your default branch, e.g., 'master'
